language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
 - 5.4

env:
  global:
    - IGNORE_PATHS=ignore
    - IGNORE_NAMES=ignore_name.php
    - COVERAGE=false
    - DB=pgsql
  matrix:
    - MOODLE_BRANCH=MOODLE_29_STABLE
    - MOODLE_BRANCH=MOODLE_28_STABLE
    - MOODLE_BRANCH=MOODLE_27_STABLE DB=mysqli

matrix:
  include:
    - php: 7.0
      env: MOODLE_BRANCH=MOODLE_30_STABLE
    - php: 7.0
      env: MOODLE_BRANCH=MOODLE_31_STABLE COVERAGE=true
    - php: 7.0
      env: MOODLE_BRANCH=master

install:
  # Several tools complain about xdebug slowdown.
  - phpenv config-rm xdebug.ini

  - composer selfupdate
  - composer install --no-interaction --prefer-dist

  # Mimic how a Moodle plugin would be run.
  - cp -R tests/Fixture/moodle-local_travis ../moodle-local_travis
  - export PATH="$(cd bin; pwd):$(cd vendor/bin; pwd):$PATH"
  - export TRAVIS_BUILD_DIR=$(cd ../moodle-local_travis; pwd)

  # Finally, the standard install step.
  - moodle-plugin-ci install

script:
  - composer validate
  - composer lint
  - php-cs-fixer --dry-run -v fix
  - if [ "$COVERAGE" = true ]; then phpdbg -qrr $(which phpunit) --coverage-clover coverage.clover; fi
  - if [ "$COVERAGE" = false ]; then phpunit; fi

  # This is basically "integration" testing.
  - moodle-plugin-ci phplint
  - moodle-plugin-ci phpcpd
  - moodle-plugin-ci phpmd
  - moodle-plugin-ci codechecker
  - moodle-plugin-ci codechecker --standard poet
  - moodle-plugin-ci csslint
  - moodle-plugin-ci shifter
  - moodle-plugin-ci jshint
  - moodle-plugin-ci validate
  - moodle-plugin-ci phpunit --coverage-text
  - moodle-plugin-ci behat

after_script:
  - if [ "$COVERAGE" = true ]; then wget https://scrutinizer-ci.com/ocular.phar; fi
  - if [ "$COVERAGE" = true ]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi
